version: 2.1

workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:17.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Execute tests
          command: npm run test
